name: teacher_client
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  supabase_flutter: ^2.3.3
  cached_network_image: ^3.1.0
  auto_route: ^7.8.4
  file_picker: ^6.1.1
  equatable: ^2.0.5
  intl: ^0.19.0
  web: ^0.5.1
  audioplayers: ^6.0.0
  audioplayers_web: ^5.0.0
  shared_preferences: ^2.2.3
  talker: ^4.1.3
  bloc_concurrency: ^0.2.5
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/person1.png
  uses-material-design: true
  fonts:
    - family: PT-Sans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
        - asset: assets/fonts/PTSans-BoldItalic.ttf
        - asset: assets/fonts/PTSans-Italic.ttf
